
version: 2
sources:
  - name: raw_data  # Corresponds to your schema in the warehouse
    database: user_activity_db
    tables:
      - name: posts
        description: "Raw posts data fetched from the JSONPlaceholder API."
        
      - name: comments
        description: "Raw comments data fetched from the API, linked to posts."
        
models:
  - name: stg_posts
    description: "Post Stage"
    columns:
      - name: post_id
        description: "The primary key for posts"
        data_tests:
          - unique
          - not_null

  - name: stg_comments
    description: "comment stage"
    columns:
      - name: comment_id
        description: "The primary key for comments"
        data_tests:
          - unique
          - not_null
      - name: post_id
        tests:
          - relationships:   # The test name is the key
              to: ref('stg_posts')   # Arguments are nested directly below it
              field: post_id

  - name: dim_users
    columns:
      - name: user_id
        description: "The primary keys for users"
        data_tests:
          - unique
          - not_null

   

